name: Releases to Discord

on:
  release:
    types: [ published ]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: sillyangel/releases-to-discord@v1.0.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL_RELEASES }}
          color: "2105893"
          username: "Release Changelog"
          avatar_url: "https://cdn.ougc.network/android-chrome-512x512.png"